In [6]:
import numpy as np

numlist = [[[5, 6, 7], [4, 3, 6, 8]], [[5, 6, 7]], [[5, 6, 7], [4, 3], [6, 8]]]

print(len(numlist))
print(len(numlist[0]))
print(len(numlist[1]))
print(len(numlist[2]))
print(len(numlist[2][1]))

numlist = np.array(numlist, dtype=object)

print(len(numlist))
print(len(numlist[0]))
print(len(numlist[1]))
print(len(numlist[2]))
print(len(numlist[2][1]))


3
2
1
3
2
3
2
1
3
2


In [ ]:
arr = np.array({67})
print(arr)
print(type(arr))
print(arr.ndim)

: 

In [14]:
carr1 = np.array([
               [ [1,2,3],[4,5,6],[7,8,9] ],
               [ [1,2,3],[4,5,6],[7,8,9] ],
               [ [1,2,3],[4,5,6],[7,8,9] ],
            ])
print(carr1[0][0])

[1 2 3]


In [19]:
arr = np.array([1, 2, 3, 4, 5])
arrview = arr.view()
arr[0] = 42

print(arr)
print(arrview)

[42  2  3  4  5]
[42  2  3  4  5]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
newarr = arr.reshape(2,5 )
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2,3)
newarr = arr.reshape(3, -1)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [53]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 9])
print(x)

[1 2 4]


In [61]:
arr1 = [10, 20, 30, 40]
arr2 = [4,3,2,1]

In [64]:
result = np.mod(arr1, arr2)
print(type(result))
print(result)
for i in range(len(arr1)):
    print(arr1[i]%arr2[i])
print(20%3)

<class 'numpy.ndarray'>
[2 2 0 0]
2
2
0
0
2


In [67]:
# import numpy as np

# # Read input
# arr = list(map(int, input().split()))

# # Convert to 3x3 numpy array
# result = np.array(arr,shape=(3, 3))

# # Print result
# print(result)
import numpy as np

# Read input
arr = list(map(int, input().split()))

# Convert to 3x3 numpy array
result = np.array(arr, shape=(3, 3))

# Print result
print(result)


TypeError: array() got an unexpected keyword argument 'shape'

In [68]:
import numpy as np

# Define shape when creating the array
arr = np.array([[1, 2, 3], [4, 5, 6]], shape=(2, 3))

# Print the array and its shape
print(arr)
print(arr.shape)


TypeError: array() got an unexpected keyword argument 'shape'